"""empty message

Revision ID: 282ae601504d
Revises: cbae6ac3936a
Create Date: 2017-12-12 00:31:32.028009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282ae601504d'
down_revision = 'cbae6ac3936a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_likes', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('profile')
    # ### end Alembic commands ###
