"""empty message

Revision ID: 541486d9451e
Revises: fbefe0a7b82e
Create Date: 2017-11-30 06:35:09.851350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541486d9451e'
down_revision = 'fbefe0a7b82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoid', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_likes', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('video_dislikes')
    # ### end Alembic commands ###
