"""empty message

Revision ID: 89d6b3463a2a
Revises: e9e34f4bb4b7
Create Date: 2018-01-13 00:45:30.843003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d6b3463a2a'
down_revision = 'e9e34f4bb4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_flagged_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('subjectasc', sa.Boolean(), nullable=True),
    sa.Column('subjectdesc', sa.Boolean(), nullable=True),
    sa.Column('dateasc', sa.Boolean(), nullable=True),
    sa.Column('datedesc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('save_sent_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('subjectasc', sa.Boolean(), nullable=True),
    sa.Column('subjectdesc', sa.Boolean(), nullable=True),
    sa.Column('dateasc', sa.Boolean(), nullable=True),
    sa.Column('datedesc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_likes', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('save_sent_state')
    op.drop_table('save_flagged_state')
    # ### end Alembic commands ###
