"""empty message

Revision ID: b317d84860c9
Revises: 8c8458cb5ee1
Create Date: 2018-01-24 12:06:42.661947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b317d84860c9'
down_revision = '8c8458cb5ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('save_playlist_vids', sa.Column('playlist_vid_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_likes', type_='unique')
    op.drop_column('save_playlist_vids', 'playlist_vid_id')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
