"""empty message

Revision ID: fc289b18237c
Revises: 51bb84d6bed4
Create Date: 2018-02-02 21:21:17.663508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc289b18237c'
down_revision = '51bb84d6bed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_likes', type_='unique')
    op.add_column('recipe', sa.Column('total_price', sa.FLOAT(), nullable=True))
    op.drop_column('recipe', 'price')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
